apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  resources:
  - name: my-source-repo
    type: git
  - name: my-image-resource
    type: image
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  tasks:
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    resources:
      inputs:
      - name: source
        resource: my-source-repo
      outputs:
      - name: image
        resource: my-image-resource
    params:
    - name: TLSVERIFY
      value: "false"
  - name: create-upate-deployment
    taskRef:
      name: oc-apply-deployment
    resources:
      inputs:
      - name: k8s-yamls-repo
        resource: my-source-repo
      - name: new-image
        resource: my-image-resource
    params:
    - name: deployment-name
      value: $(params.deployment-name)
    runAfter:
    - build-image
